const state = {user:null,section:"General",posts:[],users:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icon=name=>`<i data-lucide="${name}"></i>`;
function renderIcons(){window.lucide?.createIcons()}
function escapeHtml(value=""){return DOMPurify.sanitize(String(value),{ALLOWED_TAGS:[],ALLOWED_ATTR:[]})}
function formatSize(bytes){if(!Number.isFinite(bytes))return"Unknown size";if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1073741824)return`${(bytes/1048576).toFixed(1)} MB`;return`${(bytes/1073741824).toFixed(1)} GB`}
function fileIcon(name=""){const e=name.split(".").pop().toLowerCase();if(["png","jpg","jpeg","gif","webp","svg","bmp","ico"].includes(e))return"image";if(["mp4","webm","mov","avi","mkv"].includes(e))return"video";if(["mp3","wav","ogg","flac","m4a"].includes(e))return"music";if(["zip","rar","7z","tar","gz","bz2"].includes(e))return"archive";if(["pdf","doc","docx","odt","rtf"].includes(e))return"file-text";if(["xls","xlsx","csv","ods"].includes(e))return"table-2";if(["ppt","pptx","odp"].includes(e))return"presentation";if(["js","ts","html","css","json","py","lua","java","cpp","c","cs","rb","php","xml","yaml","yml"].includes(e))return"code-2";return"file"}
function showToast(message){const toast=document.createElement("div");toast.className="toast";toast.textContent=message;$("#toast-root").appendChild(toast);gsap.fromTo(toast,{y:18,opacity:0,scale:.98},{y:0,opacity:1,scale:1,duration:.28,ease:"power2.out"});setTimeout(()=>gsap.to(toast,{y:10,opacity:0,duration:.22,onComplete:()=>toast.remove()}),3000)}
async function api(url,options={}){let response;try{const token=localStorage.getItem("classdrop_token");response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}})}catch{throw new Error("Cannot reach the ClassDrop server. Make sure servers.js is running and the site is using the correct server URL.")}
let data={};const raw=await response.text();try{data=raw?JSON.parse(raw):{}}catch{data={error:raw||`Server returned ${response.status}`}}
if(!response.ok)throw new Error(data.error||`Request failed with ${response.status}`);return data}
function setAuthMode(mode){$$('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.auth===mode));$("#login-form").classList.toggle("hidden",mode!=="login");$("#signup-form").classList.toggle("hidden",mode!=="signup");$("#auth-title").textContent=mode==="login"?"Log in to ClassDrop":"Create your student account";$("#auth-copy").textContent=mode==="login"?"Access class resources, posts and shared files.":"Join your class space and start receiving shared resources.";gsap.fromTo(".auth-heading",{y:8,opacity:.3},{y:0,opacity:1,duration:.25})}
function showApp(){$("#auth-view").classList.add("hidden");$("#app-view").classList.remove("hidden");updateProfile();renderIcons();gsap.fromTo("#app-view",{opacity:0},{opacity:1,duration:.45});loadSection(state.section)}
function updateProfile(){if(!state.user)return;$("#profile-name").textContent=state.user.displayName;$("#profile-role").textContent=state.user.role;$("#profile-avatar").textContent=state.user.displayName.slice(0,1).toUpperCase();$("#teacher-tools").classList.toggle("hidden",!['teacher','owner'].includes(state.user.role));$("#owner-tools").classList.toggle("hidden",state.user.role!=="owner")}
function updateNav(section){$$('.nav-item[data-section]').forEach(item=>item.classList.toggle('active',item.dataset.section===section));$("#section-title").textContent=section;$("#feed-title").textContent=section}
async function login(username,password){const button=$("#login-form button");button.disabled=true;try{const data=await api("/api/login",{method:"POST",body:JSON.stringify({username,password})});state.user=data.user;localStorage.setItem("classdrop_token",data.token);localStorage.setItem("classdrop_session",JSON.stringify(data.user));showApp();showToast(`Welcome back, ${data.user.displayName}.`)}finally{button.disabled=false}}
async function signup(displayName,username,password){const button=$("#signup-form button");button.disabled=true;try{const data=await api("/api/signup",{method:"POST",body:JSON.stringify({displayName,username,password})});state.user=data.user;localStorage.setItem("classdrop_token",data.token);localStorage.setItem("classdrop_session",JSON.stringify(data.user));showApp();showToast("Your account is ready.")}finally{button.disabled=false}}
async function restoreSession(){const token=localStorage.getItem("classdrop_token");if(!token)return;try{const data=await api("/api/session",{method:"POST",body:"{}"});state.user=data.user;localStorage.setItem("classdrop_session",JSON.stringify(data.user));showApp()}catch{localStorage.removeItem("classdrop_token");localStorage.removeItem("classdrop_session")}}
async function loadSection(section){if(!state.user)return;state.section=section;updateNav(section);$("#owner-view").classList.add("hidden");$("#feed-view").classList.remove("hidden");const posts=$("#posts");gsap.to(posts,{opacity:.35,duration:.12});try{const data=await api(`/api/posts?section=${encodeURIComponent(section)}`);state.posts=data.posts;renderPosts()}catch(error){showToast(error.message)}finally{gsap.to(posts,{opacity:1,duration:.22})}}
function renderPosts(){const posts=$("#posts");$("#feed-count").textContent=`${state.posts.length} ${state.posts.length===1?'post':'posts'}`;$("#empty-state").classList.toggle("hidden",state.posts.length>0);posts.innerHTML=state.posts.map((post,index)=>{const description=post.description||"No description.";const short=description.length>30?`${description.slice(0,30)}...`:description;const files=(post.files||[]).map(file=>`<div class="file-card"><div class="file-icon">${icon(fileIcon(file.name))}</div><div class="file-info"><div class="file-name">${escapeHtml(file.name)}</div><div class="file-meta">${formatSize(file.size)} · ${escapeHtml(file.extension||'file')}</div></div></div>`).join("");return`<article class="post ${post.highlighted?'highlighted':''} ${post.pinned?'pinned':''}" data-post-card="${post.id}"><div class="post-top"><div><div class="post-title">${escapeHtml(post.title||'Untitled post')}</div>${post.subtitle?`<div class="post-subtitle">${escapeHtml(post.subtitle)}</div>`:''}</div><div class="post-badges">${post.pinned?`<span class="badge">${icon('pin')} Pinned</span>`:''}${post.highlighted?`<span class="badge">${icon('sparkles')} Highlight</span>`:''}</div></div><div class="post-description">${escapeHtml(short)}${description.length>30?` <span class="more">Read more</span>`:''}</div>${files?`<div class="post-files">${files}</div>`:''}<div class="post-meta"><span>${escapeHtml(post.authorName)}</span><span class="dot"></span><span>${new Date(post.createdAt).toLocaleString()}</span></div><div class="post-actions"><div class="action-group"><button class="small-btn ${post.liked?'liked':''}" data-like="${post.id}">${icon('heart')} ${post.likes||0}</button><button class="small-btn" data-open="${post.id}">${icon('message-circle')} ${post.commentCount||0}</button></div><button class="small-btn" data-open="${post.id}">Read more ${icon('arrow-up-right')}</button></div></article>`}).join("");renderIcons();if(state.posts.length)gsap.from(".post",{y:15,opacity:0,duration:.38,stagger:.055,ease:"power2.out"})}
async function toggleLike(postId){try{const data=await api(`/api/posts/${postId}/like`,{method:"POST",body:"{}"});const post=state.posts.find(p=>p.id===postId);if(post){post.likes=data.likes;post.liked=data.liked}renderPosts()}catch(error){showToast(error.message)}}
async function openPost(postId){try{const {post}=await api(`/api/posts/${postId}`);$("#detail-title").textContent=post.title||"Untitled post";const comments=(post.comments||[]).map(c=>`<div class="comment"><div class="comment-author">${escapeHtml(c.authorName)}</div><div class="comment-text">${escapeHtml(c.text)}</div></div>`).join("");const files=(post.files||[]).map(file=>`<div class="file-row file-card"><div class="file-icon">${icon(fileIcon(file.name))}</div><div class="file-info"><div class="file-name">${escapeHtml(file.name)}</div><div class="file-meta">${formatSize(file.size)} · ${escapeHtml(file.extension||'file')}</div></div><button class="file-download" data-download="${escapeHtml(file.id)}">${icon('download')}</button></div>`).join("");$("#post-detail").innerHTML=`<div class="post-meta"><span>${escapeHtml(post.authorName)}</span><span class="dot"></span><span>${escapeHtml(post.section)}</span><span class="dot"></span><span>${new Date(post.createdAt).toLocaleString()}</span></div>${post.subtitle?`<div class="post-subtitle" style="margin:12px 0">${escapeHtml(post.subtitle)}</div>`:''}<div class="detail-body">${escapeHtml(post.description||'No description.')}</div><div class="detail-files">${files||'<div class="comment-text">No files attached.</div>'}</div><div class="comments"><h3>Comments</h3>${comments||'<div class="comment-text">No comments yet.</div>'}<form class="comment-form" id="comment-form"><input id="comment-input" maxlength="500" placeholder="Write a comment..." required><button class="primary-btn" type="submit">${icon('send')}</button></form></div>`;$("#post-detail-modal").classList.remove("hidden");$("#post-detail-modal").dataset.post=post.id;renderIcons();gsap.fromTo("#post-detail-modal .modal-card",{y:25,opacity:0,scale:.97},{y:0,opacity:1,scale:1,duration:.3,ease:"power2.out"})}catch(error){showToast(error.message)}}
async function submitComment(postId,text){try{await api(`/api/posts/${postId}/comments`,{method:"POST",body:JSON.stringify({text})});await openPost(postId);await loadSection(state.section)}catch(error){showToast(error.message)}}
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type||'application/octet-stream',size:file.size,data:reader.result});reader.onerror=()=>reject(new Error(`Could not read ${file.name}`));reader.readAsDataURL(file)})}
async function createPost(){const files=[...$("#post-files").files];if(files.length>5){showToast("You can upload up to 5 files.");return}const button=$("#post-form button[type=submit]");button.disabled=true;try{const encodedFiles=[];for(const file of files)encodedFiles.push(await readFile(file));const payload={title:$("#post-title").value.trim(),subtitle:$("#post-subtitle").value.trim(),description:$("#post-description").value.trim(),section:$("#post-section").value,pinned:$("#post-pin").checked,highlighted:$("#post-highlight").checked,notify:$("#post-notify").checked,files:encodedFiles};await api("/api/posts",{method:"POST",body:JSON.stringify(payload)});$("#post-form").reset();$("#file-preview").innerHTML="";closeModals();state.section=payload.section;await loadSection(state.section);showToast("Post published.")}catch(error){showToast(error.message)}finally{button.disabled=false}}
async function downloadFile(fileId){window.open(`/api/files/${encodeURIComponent(fileId)}`,"_blank","noopener")}
async function loadOwnerPanel(){if(state.user.role!=="owner")return;try{const data=await api("/api/admin/users");state.users=data.users;$("#feed-view").classList.add("hidden");$("#owner-view").classList.remove("hidden");$("#section-title").textContent="Owner panel";$("#section-kicker").textContent="Administration";$("#accounts").innerHTML=state.users.map(user=>`<div class="account"><div><div class="account-name">${escapeHtml(user.displayName)} · @${escapeHtml(user.username)}</div><div class="account-info">${escapeHtml(user.role)} · ${escapeHtml(user.status)} · ${new Date(user.createdAt).toLocaleDateString()}</div></div><div class="account-actions">${user.username==='WVOwner'?'<span class="count-pill">Owner</span>':`<select data-role="${user.id}"><option value="student" ${user.role==='student'?'selected':''}>Student</option><option value="teacher" ${user.role==='teacher'?'selected':''}>Teacher</option></select><button class="neutral-btn" data-mute="${user.id}">${user.status==='muted'?'Unmute':'Mute'}</button><button class="danger-btn" data-ban="${user.id}">${user.status==='banned'?'Unban':'Ban'}</button>`}</div></div>`).join("");renderIcons();gsap.from(".account",{y:10,opacity:0,duration:.3,stagger:.04})}catch(error){showToast(error.message)}}
async function changeRole(userId,role){try{await api(`/api/admin/users/${userId}/role`,{method:"POST",body:JSON.stringify({role})});showToast("Role updated.");loadOwnerPanel()}catch(error){showToast(error.message)}}
async function changeStatus(userId,action){try{await api(`/api/admin/users/${userId}/status`,{method:"POST",body:JSON.stringify({action})});showToast("Account updated.");loadOwnerPanel()}catch(error){showToast(error.message)}}
function openProfile(){$("#profile-modal-name").textContent=state.user.displayName;$("#profile-modal-body").innerHTML=`<div class="profile-details"><div class="profile-detail"><span>Username</span><span>@${escapeHtml(state.user.username)}</span></div><div class="profile-detail"><span>Role</span><span>${escapeHtml(state.user.role)}</span></div><div class="profile-detail"><span>Status</span><span>${escapeHtml(state.user.status)}</span></div></div>`;$("#profile-modal").classList.remove("hidden");renderIcons();gsap.fromTo("#profile-modal .modal-card",{y:20,opacity:0},{y:0,opacity:1,duration:.28})}
function closeModals(){$$('.modal').forEach(modal=>{if(!modal.classList.contains('hidden'))gsap.to(modal,{opacity:0,duration:.15,onComplete:()=>{modal.classList.add('hidden');modal.style.opacity='' }})})}
function logout(){localStorage.removeItem("classdrop_session");localStorage.removeItem("classdrop_token");location.reload()}
$("#login-form").addEventListener("submit",async e=>{e.preventDefault();try{await login($("#login-username").value.trim(),$("#login-password").value)}catch(error){showToast(error.message)}});
$("#signup-form").addEventListener("submit",async e=>{e.preventDefault();try{await signup($("#signup-name").value.trim(),$("#signup-username").value.trim(),$("#signup-password").value)}catch(error){showToast(error.message)}});
$$('.auth-tab').forEach(tab=>tab.addEventListener('click',()=>setAuthMode(tab.dataset.auth)));
$$('.nav-item[data-section]').forEach(item=>item.addEventListener('click',()=>{$("#sidebar").classList.remove('open');loadSection(item.dataset.section)}));
$("#open-menu").addEventListener('click',()=>$("#sidebar").classList.add('open'));$("#close-menu").addEventListener('click',()=>$("#sidebar").classList.remove('open'));$("#sidebar-backdrop").addEventListener('click',()=>$("#sidebar").classList.remove('open'));$("#refresh-btn").addEventListener('click',()=>loadSection(state.section));$("#logout-btn").addEventListener('click',logout);$("#profile-btn").addEventListener('click',openProfile);$("#new-post-btn").addEventListener('click',()=>{$("#post-section").value=state.section;$("#post-modal").classList.remove('hidden');gsap.fromTo("#post-modal .modal-card",{y:25,opacity:0,scale:.97},{y:0,opacity:1,scale:1,duration:.3})});$("#owner-panel-btn").addEventListener('click',loadOwnerPanel);$$('.close-modal').forEach(b=>b.addEventListener('click',closeModals));
document.addEventListener('click',e=>{const like=e.target.closest('[data-like]'),open=e.target.closest('[data-open]'),download=e.target.closest('[data-download]'),role=e.target.closest('[data-role]'),mute=e.target.closest('[data-mute]'),ban=e.target.closest('[data-ban]');if(like)toggleLike(like.dataset.like);if(open)openPost(open.dataset.open);if(download)downloadFile(download.dataset.download);if(role)changeRole(role.dataset.role,role.value);if(mute)changeStatus(mute.dataset.mute,'toggle-mute');if(ban)changeStatus(ban.dataset.ban,'toggle-ban')});
$("#post-form").addEventListener('submit',e=>{e.preventDefault();createPost()});$("#post-files").addEventListener('change',()=>{const files=[...$("#post-files").files];$("#file-preview").innerHTML=files.slice(0,5).map(f=>`<div class="preview-item">${escapeHtml(f.name)} · ${formatSize(f.size)}</div>`).join('');if(files.length>5)showToast('Only the first 5 files will be accepted.')});$("#post-detail").addEventListener('submit',e=>{if(e.target.id!=='comment-form')return;e.preventDefault();submitComment($("#post-detail-modal").dataset.post,$("#comment-input").value.trim())});
renderIcons();restoreSession();
