const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const {URL}=require("url");
const PORT=Number(process.env.PORT||3000);
const BIN_ID="6a996f27da38895dfe33dbb4";
const JSONBIN_KEY=process.env.JSONBIN_MASTER_KEY;
const OWNER_PASSWORD=process.env.CLASSDROP_OWNER_PASSWORD||"";
const root=__dirname;
const uploadsDir=path.join(root,"uploads");
const binUrl=`https://api.jsonbin.io/v3/b/${BIN_ID}`;
const sessions=new Map();
const defaultData={users:[],posts:[],comments:[],notifications:[],settings:{siteName:"ClassDrop",maxFilesPerPost:5,sections:["General","My Class","Off Topic"]}};
if(!JSONBIN_KEY){console.error("Missing JSONBIN_MASTER_KEY.");process.exit(1)}
if(!OWNER_PASSWORD){console.error("Missing CLASSDROP_OWNER_PASSWORD.");process.exit(1)}
fs.mkdirSync(uploadsDir,{recursive:true});
function id(){return crypto.randomBytes(12).toString("hex")}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return`${salt}:${crypto.scryptSync(password,salt,64).toString("hex")}`}
function checkPassword(password,stored){try{const [salt,expected]=String(stored).split(":");if(!salt||!expected)return false;const actual=crypto.scryptSync(password,salt,64).toString("hex");return crypto.timingSafeEqual(Buffer.from(actual,"hex"),Buffer.from(expected,"hex"))}catch{return false}}
function normalizeData(data={}){return{users:Array.isArray(data.users)?data.users:[],posts:Array.isArray(data.posts)?data.posts:[],comments:Array.isArray(data.comments)?data.comments:[],notifications:Array.isArray(data.notifications)?data.notifications:[],settings:{...defaultData.settings,...(data.settings||{})}}}
function cleanUser(user){return{id:user.id,username:user.username,displayName:user.displayName,role:user.role,status:user.status,createdAt:user.createdAt}}
async function jsonbinRequest(url,options={}){let response;try{response=await fetch(url,{...options,headers:{"X-Master-Key":JSONBIN_KEY,"Content-Type":"application/json",...(options.headers||{})}})}catch{throw new Error("Could not reach JSONBin. Check the server internet connection.")};const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok){const message=data.message||data.error||data.errorMessage||text||`HTTP ${response.status}`;throw new Error(`JSONBin ${response.status}: ${message}`)}return data}
async function readBin(){const result=await jsonbinRequest(`${binUrl}/latest`);return normalizeData(result.record)}
async function writeBin(data){return jsonbinRequest(binUrl,{method:"PUT",headers:{"X-Bin-Versioning":"true"},body:JSON.stringify(normalizeData(data))})}
async function ensureOwner(data){let owner=data.users.find(u=>u.username.toLowerCase()==="wvowner");if(!owner){owner={id:id(),username:"WVOwner",displayName:"WVOwner",passwordHash:hashPassword(OWNER_PASSWORD),role:"owner",status:"active",createdAt:new Date().toISOString()};data.users.push(owner);await writeBin(data)}return owner}
function send(res,status,payload){const body=JSON.stringify(payload);res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, OPTIONS"});res.end(body)}
function text(res,status,body,type="text/plain; charset=utf-8"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store"});res.end(body)}
function body(req){return new Promise((resolve,reject)=>{let size=0;const chunks=[];const limit=160*1024*1024;req.on("data",chunk=>{size+=chunk.length;if(size>limit){reject(new Error("Request is too large. Keep uploads below 150 MB."));req.destroy();return}chunks.push(chunk)});req.on("end",()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")||"{}"))}catch{reject(new Error("Invalid JSON request."))}});req.on("error",reject)})}
function token(req){const header=req.headers.authorization||"";return header.startsWith("Bearer ")?header.slice(7):""}
function userFrom(req,data){const userId=sessions.get(token(req));return data.users.find(u=>u.id===userId&&u.status!=="banned")||null}
function requireUser(req,data){const user=userFrom(req,data);if(!user)throw new Error("You need to log in again.");if(user.status==="muted")throw new Error("Your account is muted.");return user}
function requireTeacher(req,data){const user=requireUser(req,data);if(!["teacher","owner"].includes(user.role))throw new Error("Teacher access required.");return user}
function requireOwner(req,data){const user=requireUser(req,data);if(user.role!=="owner")throw new Error("Owner access required.");return user}
function safeFileName(name){return path.basename(name).replace(/[^\w.\- ()[\]]/g,"_").slice(0,180)}
function ext(name){return path.extname(name).replace(".","").toLowerCase()||"file"}
function saveFile(file){if(!file?.name||!file?.data)throw new Error("Invalid file.");const comma=file.data.indexOf(",");if(comma<0)throw new Error("Invalid file data.");const buffer=Buffer.from(file.data.slice(comma+1),"base64");const fileId=id();const storedName=`${fileId}-${safeFileName(file.name)}`;fs.writeFileSync(path.join(uploadsDir,storedName),buffer);return{id:fileId,name:safeFileName(file.name),size:buffer.length,type:file.type||"application/octet-stream",extension:ext(file.name),storedName}}
function publicPost(post,data,viewer){const comments=data.comments.filter(c=>c.postId===post.id);return{id:post.id,authorName:post.authorName,section:post.section,title:post.title,subtitle:post.subtitle,description:post.description,files:post.files,pinned:Boolean(post.pinned),highlighted:Boolean(post.highlighted),createdAt:post.createdAt,liked:Array.isArray(post.likedBy)?post.likedBy.includes(viewer.id):false,likes:Array.isArray(post.likedBy)?post.likedBy.length:0,commentCount:comments.length,comments:comments.map(c=>({id:c.id,authorName:c.authorName,text:c.text,createdAt:c.createdAt}))}}
function removeFiles(post){for(const file of post.files||[]){const p=path.join(uploadsDir,file.storedName);if(fs.existsSync(p))fs.unlinkSync(p)}}
function fileFor(data,fileId){for(const post of data.posts){const file=(post.files||[]).find(f=>f.id===fileId);if(file)return{post,file}}return null}
async function handle(req,res){if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, OPTIONS"});return res.end()}
const url=new URL(req.url,`http://${req.headers.host}`);const pathname=url.pathname;
if(pathname==="/api/health"&&req.method==="GET"){const data=await readBin();send(res,200,{ok:true,users:data.users.length,posts:data.posts.length});return}
if(pathname.startsWith("/api/")){const data=await readBin();
if(pathname==="/api/signup"&&req.method==="POST"){const b=await body(req);const displayName=String(b.displayName||"").trim();const username=String(b.username||"").trim();const password=String(b.password||"");if(displayName.length<1||displayName.length>50)throw new Error("Enter a valid display name.");if(!/^[a-zA-Z0-9_.-]{3,30}$/.test(username))throw new Error("Username must be 3-30 characters and use letters, numbers, dots, dashes or underscores.");if(password.length<8)throw new Error("Password must be at least 8 characters.");if(username.toLowerCase()==="wvowner")throw new Error("That username is reserved.");if(data.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw new Error("Username is already taken.");const user={id:id(),username,displayName,passwordHash:hashPassword(password),role:"student",status:"active",createdAt:new Date().toISOString()};data.users.push(user);await writeBin(data);const session=crypto.randomBytes(32).toString("hex");sessions.set(session,user.id);send(res,200,{user:cleanUser(user),token:session});return}
if(pathname==="/api/login"&&req.method==="POST"){const b=await body(req);const username=String(b.username||"").trim();const password=String(b.password||"");const user=data.users.find(u=>u.username.toLowerCase()===username.toLowerCase());if(!user||!checkPassword(password,user.passwordHash))throw new Error("Invalid username or password.");if(user.status==="banned")throw new Error("This account is banned.");const session=crypto.randomBytes(32).toString("hex");sessions.set(session,user.id);send(res,200,{user:cleanUser(user),token:session});return}
if(pathname==="/api/session"&&req.method==="POST"){const user=requireUser(req,data);send(res,200,{user:cleanUser(user)});return}
if(pathname==="/api/posts"&&req.method==="GET"){const user=requireUser(req,data);const section=url.searchParams.get("section");if(!data.settings.sections.includes(section))throw new Error("Invalid section.");const posts=data.posts.filter(p=>p.section===section).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||new Date(b.createdAt)-new Date(a.createdAt)).map(p=>publicPost(p,data,user));send(res,200,{posts});return}
if(pathname==="/api/posts"&&req.method==="POST"){const user=requireTeacher(req,data);const b=await body(req);if(!data.settings.sections.includes(b.section))throw new Error("Invalid section.");const incoming=Array.isArray(b.files)?b.files:[];if(incoming.length>5)throw new Error("You can upload up to 5 files.");const files=incoming.map(saveFile);const post={id:id(),authorId:user.id,authorName:user.displayName,section:b.section,title:String(b.title||"").trim().slice(0,120),subtitle:String(b.subtitle||"").trim().slice(0,160),description:String(b.description||"").trim().slice(0,4000),files,pinned:Boolean(b.pinned),highlighted:Boolean(b.highlighted),createdAt:new Date().toISOString(),likedBy:[]};data.posts.push(post);if(b.notify){const recipients=data.users.filter(u=>u.id!==user.id&&u.status!=="banned");for(const recipient of recipients)data.notifications.push({id:id(),userId:recipient.id,postId:post.id,text:`${user.displayName} shared a new post.`,createdAt:new Date().toISOString(),read:false})}await writeBin(data);send(res,200,{post:publicPost(post,data,user)});return}
const postMatch=pathname.match(/^\/api\/posts\/([^/]+)$/);if(postMatch&&req.method==="GET"){const user=requireUser(req,data);const post=data.posts.find(p=>p.id===postMatch[1]);if(!post)throw new Error("Post not found.");send(res,200,{post:publicPost(post,data,user)});return}
const likeMatch=pathname.match(/^\/api\/posts\/([^/]+)\/like$/);if(likeMatch&&req.method==="POST"){const user=requireUser(req,data);const post=data.posts.find(p=>p.id===likeMatch[1]);if(!post)throw new Error("Post not found.");post.likedBy=Array.isArray(post.likedBy)?post.likedBy:[];const index=post.likedBy.indexOf(user.id);if(index>=0)post.likedBy.splice(index,1);else post.likedBy.push(user.id);await writeBin(data);send(res,200,{likes:post.likedBy.length,liked:index<0});return}
const commentMatch=pathname.match(/^\/api\/posts\/([^/]+)\/comments$/);if(commentMatch&&req.method==="POST"){const user=requireUser(req,data);if(!data.posts.some(p=>p.id===commentMatch[1]))throw new Error("Post not found.");const b=await body(req);const commentText=String(b.text||"").trim();if(!commentText||commentText.length>500)throw new Error("Comment must be 1-500 characters.");data.comments.push({id:id(),postId:commentMatch[1],authorId:user.id,authorName:user.displayName,text:commentText,createdAt:new Date().toISOString()});await writeBin(data);send(res,200,{ok:true});return}
if(pathname.startsWith("/api/files/")&&req.method==="GET"){requireUser(req,data);const fileId=pathname.split("/").pop();const result=fileFor(data,fileId);if(!result)throw new Error("File not found.");const file=result.file;const p=path.join(uploadsDir,file.storedName);if(!fs.existsSync(p))throw new Error("File is missing from the server storage.");res.writeHead(200,{"Content-Type":file.type||"application/octet-stream","Content-Disposition":`attachment; filename="${file.name.replace(/"/g,"_")}"`,"Cache-Control":"private, max-age=0"});fs.createReadStream(p).pipe(res);return}
if(pathname==="/api/admin/users"&&req.method==="GET"){requireOwner(req,data);send(res,200,{users:data.users.map(cleanUser)});return}
const roleMatch=pathname.match(/^\/api\/admin\/users\/([^/]+)\/role$/);if(roleMatch&&req.method==="POST"){const owner=requireOwner(req,data);const b=await body(req);const user=data.users.find(u=>u.id===roleMatch[1]);if(!user)throw new Error("User not found.");if(user.id===owner.id)throw new Error("The owner role cannot be changed.");if(!["student","teacher"].includes(b.role))throw new Error("Invalid role.");user.role=b.role;await writeBin(data);send(res,200,{user:cleanUser(user)});return}
const statusMatch=pathname.match(/^\/api\/admin\/users\/([^/]+)\/status$/);if(statusMatch&&req.method==="POST"){const owner=requireOwner(req,data);const b=await body(req);const user=data.users.find(u=>u.id===statusMatch[1]);if(!user)throw new Error("User not found.");if(user.id===owner.id)throw new Error("You cannot moderate the owner account.");if(b.action==="toggle-mute")user.status=user.status==="muted"?"active":"muted";else if(b.action==="toggle-ban")user.status=user.status==="banned"?"active":"banned";else throw new Error("Invalid moderation action.");await writeBin(data);send(res,200,{user:cleanUser(user)});return}
throw new Error("API route not found.")}
if(req.method==="GET"){const requested=pathname==="/"?"index.html":pathname.slice(1);const filePath=path.resolve(root,requested);if(!filePath.startsWith(root))return text(res,403,"Forbidden");if(!fs.existsSync(filePath)||fs.statSync(filePath).isDirectory())return text(res,404,"Not found");const types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".json":"application/json; charset=utf-8"};res.writeHead(200,{"Content-Type":types[path.extname(filePath).toLowerCase()]||"application/octet-stream"});fs.createReadStream(filePath).pipe(res);return}
text(res,405,"Method not allowed")}
async function start(){const data=await readBin();await ensureOwner(data);const server=http.createServer((req,res)=>handle(req,res).catch(error=>{console.error(error);send(res,400,{error:error.message||"Request failed."})}));server.listen(PORT,()=>console.log(`ClassDrop running at http://localhost:${PORT}`))}
start().catch(error=>{console.error(error);process.exit(1)});
